baseURL = "https://yibocat.github.io/"
title = "Yibocat"
theme = "notepadium"
copyright = "Â©2022 Yibocat."

# languageCode = "zh-cn"
hasCJKLanguage = true
enableRobotsTXT = true
defaultContentLanguage = 'zh'     # æ›´æ”¹è¯­è¨€
# Enable Disqus
#disqusShortname = "XXX"
# Google Analytics
# googleAnalytics = "UA-123-45"
[outputs]                         # home åŠ è½½é¡¹
  home = ["HTML","RSS","JSON"]
[markup.highlight]
  codeFences = true
  noClasses = false

[markup.goldmark.renderer]        # å…è®¸åœ¨ Markdown ä¸­åµŒå…¥ Html ä»£ç 
  unsafe = true  # enable raw HTML in Markdown

[params]                          # ç½‘ç«™é…ç½®é€‰é¡¹
  style = "auto"                  # default: auto. light: light theme, dark: dark theme, auto: based on system.
  dateFormat = "2006-01-02"       # if unset, default is "2006-01-02"  ä¸èƒ½è®¾ç½®æˆ 2006-01-01 ï¼ï¼ï¼ï¼ è¿™æ ·æ—¥æœŸçš„æœˆå’Œæ—¥å°±ä¼šä¸€æ ·äº†ï¼ï¼ï¼
  readingTime = true              # show reading time after article date
  logo = "/images/yibo_1.jpeg"        # if you have a logo png
  slogan = ""
  license = "ç‰ˆæƒå£°æ˜ï¼šå¦‚æœè½¬å‘è¯·å¸¦ä¸Šæœ¬æ–‡é“¾æ¥å’Œæ³¨æ˜æ¥æºã€‚"                  # CC License
  fullRss = false                 # Puts entire HTML post into rss 'description' tag. If unset, default is false.
  ipv6ready = true                # Show IPV6Ready logo on footer.
  avatar = "/images/yibo_1.jpeg"    # å¤´åƒ
  ShowToc = true                  # æ˜¾ç¤º table of content 

[params.heatmap]                  # çƒ­åŠ›æ—¥å†å›¾
  heatmap = true

[params.intro]                    # é¦–é¡µç®€ä»‹
  intro_1 = "## **å¥½è®°æ€§ä¸å¦‚çƒ‚ç¬”å¤´** ##"        # é¦–é¡µç®€ä»‹ 1
  intro_2 = "**Keywords**: ğŸ’»python | ğŸ‘¾Minecraft| ğŸ€ | ğŸ˜¶â€ğŸŒ«ï¸Fuzzy Set."               # é¦–é¡µç®€ä»‹ 2
  intro_3 = "**Status**: ğŸ“–"               # é¦–é¡µç®€ä»‹ 3
[params.profile]                  # æ–‡ç« åº•éƒ¨ç­¾åè®¾ç½®
  enable = true
  avatar = "/json/77907-vault.json"
  name = "yibocat"
  bio = "è„‘å­ä¸å¤Ÿé”®ç›˜æ¥å‡‘"  # support markdown syntax
  # twitter = "GoHugoIO"  # https://twitter.com/XXX
  github = "yibocat"  # https://github.com/XXX
  email = "yibocat@yeah.net"


[params.assets]                   # èµ„äº§åº“ï¼ˆåŒ…æ‹¬ css å’Œ jsï¼‰
  css = ["css/fonts.css","css/archive.css","css/custom_style.css"]
  js = ["js/copy-to-clipboard.js","js/toc.js"]
[params.comments]                 # å¼€å¯è¯„è®º
  enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.
[params.comments.utterances]      # è¯„è®ºæ’ä»¶
  repo = "MetalBlueberry/MetalBlueberry.github.io" # enable comments with [utteranc.es](https://utteranc.es/)

[params.math]                     # æ•°å­¦å…¬å¼æ’ä»¶
  enable = true  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
  use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]                   # ä¸»é¢˜é€‰æ‹©
  use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
  theme = "dracula"  #  å¯è¡Œï¼šChroma:draculaã€friendly      hljs:agate  atom-one-dark
  darkTheme = "solarized-dark256"  # apply this theme in dark mode # å¯è¡Œï¼šfruity github-dark rrt solarized-dark256    hljs:zenburn

[params.share]                    # åˆ†äº«
  enable = false
  addThisId = "ra-1234567890"
  inlineToolId = "æµ‹è¯•åˆ†äº«"



[params.social]                   # ç¤¾äº¤æ ‡ç­¾è‡ªå®šä¹‰
    GitHub = "yibocat"
    Email   = "yibocat@yeah.net"
    # Weibo = "yibocat"
    # Steam = "yibooo"
    Zhihu = "yibocat"
    # Linkedin = "xxxx"
    # Twitter = "xxxx"
    # Instagram = "xxxx"
    # Facebook = "xxxx"
    # Telegram = "xxxx"
    # Medium = "xxxx"
    # Gitlab = "xxxx"
    # Youtubelegacy = "xxxx"
    # Youtubecustom = "xxxx"
    # Youtubechannel = "xxxx"
    # Tumblr ="xxxx"
    # Quora = "xxxx"
    # Keybase = "xxxx"
    # Pinterest = "xxxx"
    # Reddit = "xxxx"
    # Codepen = "xxxx"
    # Bitbucket = "xxxx"
    # Stackoverflow = "xxxxx"
    # Odnoklassniki = "xxxx"
    # VKontakte = "xxxx"
    # Flickr = "xxxx"
    # Xing = "xxxx"
    # Snapchat = "xxxx"
    # Soundcloud = "xxxx"
    # Spotify = "xxxx"
    # Bandcamp = "xxxx"
    # Paypal = "xxxx"
    # Fivehundredpx = "xxxx"
    # Mix = "xxxx"
    # Goodreads = "xxxx"
    # Lastfm = "xxxx"
    # Foursquare = "xxxx"
    # Hackernews = "xxxx"
    # Kickstarter = "xxxx"
    # Patreon = "xxxx"
    # Twitch = "xxxx"
    # Strava = "xxxx"
    # Skype = "xxxx"
    # Whatsapp = "xxxx"
    # Douban = "xxxx"
    # Angellist = "xxxx"
    # Slidershare = "xxxx"
    # Jsfiddle = "xxxx"
    # Deviantart = "xxxx"
    # Behance = "xxxx"
    # Dribble = "xxxx"
    # Wordpress = "xxxx"
    # Vine = "xxxx"
    # Googlescholar = "xxxx"
    # Researchgate = "xxxx"
    # Mastodon = "xxxx"
    # Thingiverse = "xxxx"


[params.nav]                      # è‡ªå®šä¹‰èœå•
  showCategories = true           # /categories/
  showTags = true                # /tags/
  showArchives = true
  showSearch = true
  showPosts = true

[params.navbottom]                # åº•éƒ¨èœå•
  showCategories = true           # /categories/
  showTags = true                 # /tags/
  showArchives = true
  showSearch = true
  showPosts = true
[[params.nav.custom]]             # è‡ªå®šä¹‰å¤–éƒ¨èœå•
  # title = "About"
  # url = "/about"



[params.beian]                    # å¤‡æ¡ˆè®¾ç½®
  icp = ""     # example: ç²¤ICPå¤‡20056596å·-1
  gongan = ""  # example: ç²¤å…¬ç½‘å®‰å¤‡ 44030502005645å·
  code = ""    # example: 44030502005645